name:           AJAX Login
version:        0.9.2
description:    Provides Movable Type with a framework to support logging in via AJAX.
plugin_author:  "Endevver, LLC."
static_version: 1
plugin_class:   AJAXLogin
id:             AJAXLogin
key:            AJAXLogin

applications:
  comments:
    methods:
      do_ajax_login: $AJAXLogin::AJAXLogin::Plugin::ajax_login
